model: "unet"

spatial_dims: 2
in_channels: 1
out_channels: 16
channels: [32, 64, 128, 256, 512]
num_workers: 2

strides: [2, 2, 2, 2]
num_res_units: 2  
kernel_size: 3
up_kernel_size: 3
dropout: 0.0
bias: True
adn_ordering: "NDA"  

act: ["LeakyReLU", {"negative_slope": 0.1, "inplace": True}]
norm: ["instance", {"affine": True}]